### ISSUE TITLE
add command doesn't work anymore

### ISSUE THREAD

**Issue by ClementDBS** [c3pm-labs/c3pm#33]
**Describe the bug**

the add command succeeds to install the library into the .c3pm directory. However, the build can't find the library afterward.

**To Reproduce**
- Delete your .c3pm in your home directory
- Create a project who use asio
- add the asio library
- build the project

**Expected behavior**
A description of what you expected to happen.
The project should compile.

**Please tell us about your environment:**
  - Version: last version
  - OS: macOS

**Comment by Codelax** [comment]
Let's look at asio c3pm.yml
```yaml
c3pm_version: v1
type: library
name: asio
description: ""
version: 1.12.0
license: UNLICENSED
files:
  sources:
  - './src/*.cpp'
  includes:
  - 'include/**/*.hpp'
  - 'include/**/*.ipp'
  include_dirs:
  - include
  - include/boost
  exported_dir: 'include'
  exported_include_dirs:
    - 'include'
    - 'include/boost'
dependencies: {}
```

When compiling your project it will include `~/.c3pm/cache/asio/1.12.0/include`.
But as `exported_dir` is `include`, content of the include folder of asio was installed in `~/.c3pm/cache/asio/1.12.0` so we have:
```
├── cache
│   ├── asio
│   │   └── 1.12.0
│   │       ├── boost
│   │       ├── c3pm.yml
│   │       └── lib
```

If `exported_dir` was left empty we would have `1.12.0/include/boost` instead of `1.12.0/boost`.

We need to work on clarity of c3pm.yml, there is no information about `exported_dir` in [spec](https://github.com/c3pm-labs/specs).
We should rework config's content.
